### ISSUE TITLE
CALL H2GIS_SPATIAL() after CALL SHPRead not possible

### ISSUE THREAD

**Issue by edigonzales** [orbisgis/h2gis#1200] opened 2021-03-11 14:47 UTC
Executing `CALL H2GIS_SPATIAL()` (for a second time) after executing `CALL SHPRead()` does not work:

```
org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.SYS(ID)"; SQL statement:
COMMENT ON ALIAS ST_GeometryTypeCode IS ? [23505-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:123)
        at org.h2.mvstore.db.MVTable.addRow(MVTable.java:732)
        at org.h2.engine.Database.addMeta(Database.java:888)
        at org.h2.engine.Database.addDatabaseObject(Database.java:1080)
        at org.h2.command.ddl.SetComment.update(SetComment.java:114)
        at org.h2.command.CommandContainer.update(CommandContainer.java:102)
        at org.h2.command.Command.executeUpdate(Command.java:261)
        at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:249)
        at org.h2gis.functions.factory.H2GISFunctions.registerFunction(H2GISFunctions.java:488)
        at org.h2gis.functions.factory.H2GISFunctions.registerFunction(H2GISFunctions.java:445)
        at org.h2gis.functions.factory.H2GISFunctions.registerH2GISFunctions(H2GISFunctions.java:539)
        at org.h2gis.functions.factory.H2GISFunctions.load(H2GISFunctions.java:352)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.h2.engine.FunctionAlias$JavaMethod.getValue(FunctionAlias.java:456)
        at org.h2.expression.JavaFunction.getValue(JavaFunction.java:38)
        at org.h2.command.dml.Call.query(Call.java:65)
        at org.h2.command.CommandContainer.query(CommandContainer.java:114)
        at org.h2.command.Command.executeQuery(Command.java:202)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:227)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
        at h2gistest.App.main(App.java:19)
```

```
            stmt.execute("CREATE ALIAS IF NOT EXISTS H2GIS_SPATIAL FOR \"org.h2gis.functions.factory.H2GISFunctions.load\"");
            stmt.execute("CREATE ALIAS IF NOT EXISTS H2GIS_UNLOAD FOR \"org.h2gis.functions.factory.H2GISFunctions.unRegisterH2GISFunctions\"");
            stmt.execute("CALL H2GIS_SPATIAL();");
            stmt.execute("SELECT 1");
            stmt.execute("CALL SHPRead('/Users/stefan/sources/h2gis-tests/app/src/data/netz7.shp', 'netz7')");
            stmt.execute("CALL H2GIS_SPATIAL();");
```

Code above works without the `CALL SHPRead` query. 

Version 1.5.

**Comment by ebocher** [comment] 2021-11-15 16:24
I close this issue because I cannot reproduce it.
A unit test has been added  here https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/test/java/org/h2gis/functions/RegressionTest.java#L50

**Closed by ebocher** 2021-11-15 16:24 UTC
